### ISSUE TITLE
Allow passing an array of mime-types

### ISSUE THREAD

**Issue by okonet** [okonet/attr-accept#3]
Moved from https://github.com/okonet/react-dropzone/issues/243

> When passing in an array of mime types, it is correctly limiting available selections for the onClick file selector (non-accepted files are greyed out), but drag and drop does not work and it throws an error in the console saying that a string should be passed. Would it be possible to enable an array of mimetypes?

**Comment by Nolski** [comment]
The HTML5 spec states that accept will take a "list of values" which is then describes as comma separated strings. Since this is a javascript implementation, I think it is reasonable to also accept an array since semantically they are the same thing.

https://www.w3.org/TR/html-markup/input.file.html#input.file.attrs.accept

**Comment by okonet** [comment]
https://www.w3.org/TR/html-markup/datatypes.html#data-comma-separated-strings describes it as

> Zero or more strings that are themselves each zero or more characters, each optionally with leading and/or trailing space characters, and each separated from the next by a single "," (comma) character. Each string itself must not begin or end with any space characters, and each string itself must not contain any "," (comma) characters.

so yeah, looks similar to an `Array<String>` signature.

Mind submitting a PR for that?

**Comment by Nolski** [comment]
Yeah, I'll see if I can submit it sometime this week.
